### ISSUE TITLE
Error: Cannot Open URL

### ISSUE THREAD

**Issue by BW1010** [sewardlee337/finreportr#12]
Trying to follow along the book "Processing and Analyzing Financial Data with R" by
Marcelo S. Perlin , Ch.7. 
Similar errors ("error in download.file") occur for functions GetBalanceSheet and GetCashFlow.

![image](https://user-images.githubusercontent.com/41599947/43112125-1e6356f4-8eba-11e8-9ed8-10c5b5cbc320.png)

**Comment by sewardlee337** [comment]
Hi @BW1010,

 `GetIncome("GOOG", 2016)` is working on my end. Can you:
* Test to see if `GetIncome()` works for other symbols and/or years?
* Provide the output for `sessionInfo()`
