### ISSUE TITLE
Error in ExtractInfo(".companyName") %>% strsplit(" CIK") :    could not find function "%>%"

### ISSUE THREAD

**Issue by joeymizrahi** [sewardlee337/finreportr#14]
I keep getting this error  when running:
`CompanyInfo("GOOG")`

**Comment by sewardlee337** [comment]
Hello,

Could you check to see if you have the package `dplyr` and/or `magrittr` installed?

**Comment by joeymizrahi** [comment]
yes, they are both installed

**Comment by sewardlee337** [comment]
Was `dplyr` loaded properly? 

The error message indicates that the pipe operator was not recognized, so please confirm that the necessary packages that are needed to use the pipe operator are installed and loaded.

**Comment by joeymizrahi** [comment]
Thanks,
I had to load the dplyr,stats,base libraries before loading the finreportr library

**Comment by joeymizrahi** [comment]
Another 2 questions:
1. I see that all searches are being done by Company Ticker.
What is I wanted to do it by its CIK
2. There are years missing, is this because SEC only provides xml from a certain year?
3. This is only for 10-K filings, do you happen to have for 10-Q as well?
Thanks!

**Comment by sewardlee337** [comment]
To answer your questions:
* Searches are currently only available by ticker
* That's a reasonable assumption, but I can't say for sure without additional information. It is true that, for years farther in the past, you are more likely to not have financials in XBRL form.
* Unfortunately, not at the moment, but possibly in a future release.
